#!/bin/sh

#Specify temp file name
tempFileName=tmp$$

#Set up trap for interrupt, hangup, and terminate signals
trap "rm -f $tempFileName" INT HUP TERM EXIT

#Check for correct number of parameters
correctCmdMsg="Usage: stats {-rows|-cols} [file]"
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]
then
   echo $correctCmdMsg >&2
   exit 1
fi

#Check if the row/column args start with either "-r" or "-c"
rowArgName="-r"
colArgName="-c"
if [ "${1:0:2}" != $rowArgName ] && [ "${1:0:2}" != $colArgName ]
then
   echo $correctCmdMsg >&2
   exit 1
fi

#If file is specified, check file is readable 
if [ ! -r "$2" ] && [ "$#" -eq 2 ]
then
   fileNotExistMsg="stats: cannot read $2"
   echo $fileNotExistMsg >&2
   exit 1
fi

#Process mean and median from rows
if [ "${1:0:2}" == $rowArgName ]
then
   #Add Column header for "row" mode
   echo "Average	Median" | cat >> $tempFileName

   while read -r line
   do

      numValuesInRow=$(echo $line | wc -w)
      valuesInLine=$(echo $line | tr "	" "\n")

      #------Row Average Processing---------------

      #Find the sum of all the numbers in the row
      sumTotal=0
      for num in $valuesInLine
      do
	 #echo "[$num]" | cat >> $tempFileName
	 sumTotal=$(expr $sumTotal + $num) 
      done

      #Find the average without rounding
      rowAverage=$(expr $sumTotal / $numValuesInRow )

      #Check if we need to round up (increment if we do)
      remainder=$(expr $sumTotal % $numValuesInRow )
      doubleRemainder=$(expr $remainder \* 2 )
      if [ "$doubleRemainder" -ge "$numValuesInRow"  ]
      then
	 #If the double the remainder is greater than denominator then round up
	 rowAverage=$(expr $rowAverage + 1 )
      fi

      #------Row Median Processing---------------
      #Sort the numbers in the row
      #     Sort is done by transforming the space delimited string
      #     to a new line delimted string then sorting. Then transforming
      #     back to space delimited string
      sortedRowNums=$(echo $valuesInLine | tr " " "\n" | sort | tr "\n" " ")
      echo $sortedRowNums | cat >> $tempFileName

      #echo $rowAverage | cat >> $tempFileName
   done < "${2:-/dev/stdin}" #Read from specified file or stdin
fi

#Process mean and median from columns
if [ "${1:0:2}" == $colArgName ]
then
   echo "Implement columns processing please"
fi

cat $tempFileName
